spring:
  application:
    name: demo-acme
server:
  servlet:
    context-path: /api/acme
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operationsSorter: method
    tagsSorter: alpha
soap:
  service:
#    url: http://localhost:8080/api/acme/mock/envio-pedidos
    url: https://run.mocky.io/v3/19217075-6d4e-4818-98bc-416d1feb7b84
